name: Test and Build

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  lint-and-typecheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci  #clean install dependencies based on package-lock.json

      - name: Run Lint
        run: npm run lint     #check code for linting errors. linting errors is a code quality tool that checks for stylistic errors in code

  
  Deploy-to-AWS:
    needs: lint-and-typecheck  # first job must complete successfully before this job can run
    name: Deploy to AWS

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci  
  
      # Linting already done in previous job, so we can skip it here

      - name: Build project
        run: npm run build  #build the project
      
      - name: Deploy to AWS
        run: echo "Deploying to AWS..."  #placeholder for actual deployment command
